# Generated by Django 5.0.6 on 2024-06-29 04:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('contect', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('arrivals', models.CharField(default=' ', max_length=200)),
                ('departure', models.CharField(default=' ', max_length=100)),
                ('pax', models.CharField(default=' ', max_length=100)),
                ('stay_type', models.CharField(default=' ', max_length=100)),
                ('package', models.CharField(default=' ', max_length=200)),
                ('tariff', models.CharField(default=' ', max_length=100)),
                ('advance', models.IntegerField(default=0)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
