# Generated by Django 5.0.6 on 2024-06-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='contect',
            new_name='contact',
        ),
    ]
